apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: games-cluster
  region: us-east-1

managedNodeGroups:
  - name: games-nodes
    instanceType: t3.small
    desiredCapacity: 2
    minSize: 2
    maxSize: 4
    spot: true  # for learning purposes to save costs
